language: cpp

compiler:
- gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script:
- pushd htslib && prefix=./inst make install && popd
- mkdir -p build && \
  pushd build && \
  HTSLIB_ROOT=${PWD}/../htslib/inst \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        .. &&
  make
- "{ ./src/pac_bam_scan || true; } | grep Usage"

