language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test # g++-4.9
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - 'g++-4.9'
        - cmake
        - cmake-data
        - zlib1g-dev
      install: export CXX="g++-4.9" CC="gcc-4.9"

script:
- .travis-scripts/build.sh
